### ISSUE TITLE
void return value not recognized

### ISSUE THREAD

**Issue by aight8** [jschaf/pggen#11]
```
ERROR: generate go code: template all: template query file xxx no go type found for Postgres type void oid=2278
````

I try to call a function without a return value

```sql
-- name: Something :exec
select * something(pggen.arg('arg1'), pggen.arg('arg2'), pggen.arg('arg3'));

-- or

-- name: Something :exec
select something(pggen.arg('arg1'), pggen.arg('arg2'), pggen.arg('arg3'));
```

workaround:

```sql
-- name: Something :exec
select true from something(pggen.arg('arg1'), pggen.arg('arg2'), pggen.arg('arg3'));
```

**Comment by jschaf** [comment]
Yep, definitely a bug. I'll take a look. The main difficulty is likely figuring out what Go type pgx wants to use to decode void types. I think I can use nil anything and pgx will skip the column.

**Comment by jschaf** [comment]
Should be fixed by https://github.com/jschaf/pggen/commit/a12d23ed4510ebcfcd935addb3909202b0368b31. Let me know if that doesn't do the trick.
