### ISSUE TITLE
Using enums in composite type row results fails to compile

### ISSUE THREAD

**Issue by aight8** [jschaf/pggen#23]
I pack whole rows in composit types, the generated enum fields cannot handled by the internal ```newCompositeType``` function internally.:
I get following error:

```
Cannot use '&MyEnum{}' (type *MyEnum) as type pgtype.ValueTranscoder Type does not implement 'pgtype.ValueTranscoder'
```

**Comment by jschaf** [comment]
Drats, I think this is a bug from #22. Using the previous release should provide a work-around.
