### ISSUE TITLE
proposal: generate "queries" by stored pg function

### ISSUE THREAD

**Issue by aight8** [jschaf/pggen#25]
# Motivation

Generally allow any complex nested queries. Currently it's unclear what is possible and when pggen cannot handle it
(as a result this issue is in contract to the promising project description)

In contrast the limitation caused on pg side ("optional arguments" because no reliable argument & result type reflection is possible) are clear.

## example schema
```plpgsql
create type list_item as (
   name text,
   color text
);

create type list_stats as (
   val1 hstore,
   val2 int[]
);

create or replace function fn1(
    param1 bigint,
    page int = 1,
    item_count int = 10,
    out res_items list_item[],
    out res_stats list_stats
) language plpgsql as $$begin
    -- single or many query which fills res_items and res_stats 
    -- ex: with x as (...subquery...) select array_agg(...), array_agg(...) into res_items, res_stats
end$$;
```
keep in mind the same return values could be also created by a single statement used directly as pggen query.
this example just demonstrate the way trough stored functions since this was my initial situation I was confronted with this idea.

## example query
```sql
-- name: Fn1 :one
select fn1(
    pggen.arg('x')
);
```

My intention is to create plpgsql stored functions which takes all needed arguments once and has at least two different datasets as return values.
There could be an arbitrary number of return values. They can be arrays, single values and of course nested.

## advantages
- one function with one parameter list to create multiple datasets
- pggen (future): optional function parameters could be recognized (when create go code directly from a function signature)

## disadvantages
- increased complexity

## challenges
- OID's of the composit types or array types must be known? **when i understand correctly this is one of the main issue, right?**

## questions
- what are the current issues to support this? I saw that pggen queries all the information about the result schema like ```FindDescendantOIDs```. When some OID's must be preprocessed in pgx, maybe a preparation function (like ```PrepareAll``` in #26 ) could be a solution (since the pg binary msg format don't support more info on query time, a preparation of pgx is anyway indispensable)

## workaround
- batch execute multiple standalone queries

## unclear
- performance
  - regarding the scan process of the nested composit type arrays
  - ```call plpgsql function``` vs ```run batched prepared statements``` in general

**Comment by jschaf** [comment]
Thank you for the outstanding report!

I think what you're asking is:

> Given a function with complex `OUT` types, pggen should generate a strongly typed struct for the output.

The problem is that `fn1` has an implicit return type of `record` with an OID of 2249. I think what's happening is that Postgres uses the dynamic `record` type for any functions that have OUT parameters. A record is a dynamic type not known at runtime so there's nothing pggen can do here. If Postgres doesn't know the type then pggen won't know the type. See https://stackoverflow.com/questions/30072787.

Here's the full information from `pg_type` for the `record` OID 2249. This info is hard-coded in the Postgres catalog tables.

**OID for record type**
```json
[
  {
    "oid": 2249,
    "typname": "record",
    "typnamespace": 11,
    "typowner": 10,
    "typlen": -1,
    "typbyval": false,
    "typtype": "p",
    "typcategory": "P",
    "typispreferred": false,
    "typisdefined": true,
    "typdelim": ",",
    "typrelid": 0,
    "typelem": 0,
    "typarray": 2287,
    "typinput": "record_in",
    "typoutput": "record_out",
    "typreceive": "record_recv",
    "typsend": "record_send",
    "typmodin": "-",
    "typmodout": "-",
    "typanalyze": "-",
    "typalign": "d",
    "typstorage": "x",
    "typnotnull": false,
    "typbasetype": 0,
    "typtypmod": -1,
    "typndims": 0,
    "typcollation": 0,
    "typdefaultbin": null,
    "typdefault": null,
    "typacl": null
  }
]
```

**pg_proc details for func** - Note the return type of 2249, the record type.
```json
[
  {
    "oid": 16519,
    "proname": "composite_func_2",
    "pronamespace": 16385,
    "proowner": 10,
    "prolang": 13385,
    "procost": 100,
    "prorows": 0,
    "provariadic": 0,
    "prosupport": "-",
    "prokind": "f",
    "prosecdef": false,
    "proleakproof": false,
    "proisstrict": false,
    "proretset": false,
    "provolatile": "i",
    "proparallel": "s",
    "pronargs": 3,
    "pronargdefaults": 2,
    "prorettype": 2249,
    "proargtypes": "20 23 23",
    "proallargtypes": [20, 23, 23, 16514, 16518],
    "proargmodes": ["i", "i", "i", "o", "o"],
    "proargnames": ["param1", "page", "item_count", "res_items", "res_stats"],
    "proargdefaults": "({CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4 :constbyval true :constisnull false :location 238 :constvalue 4 [ 1 0 0 0 0 0 0 0 ]} {CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4 :constbyval true :constisnull false :location 263 :constvalue 4 [ 10 0 0 0 0 0 0 0 ]})",
    "protrftypes": null,
    "prosrc": "\nBEGIN\n  res_items := ARRAY [('foo', 'bar')::list_item];\n  res_stats := ('a=>1,a=>2'::hstore, ARRAY [param1, page, item_count])::list_stats;\nEND\n",
    "probin": null,
    "proconfig": null,
    "proacl": null
  }
]
```

-----

### Attempt 1: Use `returns table`

To get type information, maybe we can add a `RETURNS TABLE(items list_item[], stats list_stats)`. That doesn't work because you can't mix table functions with IN/OUT parameters: https://stackoverflow.com/questions/47790940.

I tried removing the out params and modifying the query to use `RETURNS TABLE` so we can try to get a better return type than `record`.

```sql
CREATE FUNCTION composite_func_3(
  param1        bigint,
  page          int = 1,
  item_count    int = 10
)
RETURNS TABLE(items list_item[], stats list_stats)
  LANGUAGE plpgsql AS $$
BEGIN
  SELECT ARRAY [('foo', 'bar')::list_item], ('a=>1,a=>2'::hstore, ARRAY [param1, page, item_count])::list_stats;
END
$$ IMMUTABLE PARALLEL SAFE;

-- Query file

-- name: CompositeFunc3 :one
SELECT composite_func_3(pggen.arg('arg1'));
```

This didn't work, the OID return type was 2249, the `record` type, so same problem as above.

-----

### Attempt 2: Use `returns setof new_type`

I got the proper type by declaring a type that matched the return value and using `setof NEW_TYPE`, like so:

```
CREATE TYPE CF3_type AS (
  items list_item[],
  stats list_stats
);

CREATE FUNCTION composite_func_3(
  param1        bigint,
  page          int = 1,
  item_count    int = 10
)
  RETURNS setof cf3_type
  LANGUAGE plpgsql AS $$
BEGIN
  SELECT ARRAY [('foo', 'bar')::list_item], ('a=>1,a=>2'::hstore, ARRAY [param1, page, item_count])::list_stats;
END
$$ IMMUTABLE PARALLEL SAFE;
```

However, that errors with:

```
infer typed named query CompositeFunc3: infer output types for query: fetch oid types: find composite types: find type for composite column items oid=16547
```


### Action items

1. Fix the attempt 2 query.

2. I don't think pggen can do anything for queries with OUT params that have a return type of `record`.  To get better type information, we'd have to parse the query, figure out the method that was called and then use the postgres catalog tables to figure out the types that correspond to OUT parameters. Overall, it seems a bit silly that Postgres doesn't know the types.

**Comment by aight8** [comment]
An idea were if it's not possible to reflect the return types functions some actions:

define the **function names** as pggen argument.
after the db is setup with the given schema, the defined functions are reflected and a go query is created for it.
polymorphic functions (when a given function name is defined multiple times with different signature) must be defined explicitly with it's signature.

```
pggen gen go \
   --schema-glob "db/schema/**/*.sql" \
   --pgfunc "fn1" \
   --func "polyfn2=polyfn2"
```

based on function info from ```pgcli``` and then ```\df+``` command to list function details. it uses sql for the listed function information so I think this is a good starting point:

**Schema** could be defined by passing function with the schema "public.fn1", default is "public"
**Name** is the function name itself without any args. It creates the fundament of the naming of the call function in go.
**Result data type** contains the signature like:
- text
- TABLE(type text, oid oid, schema text, name text, params text)
- integer[]
- void
- record
**Argument data types** contains the signature like:
- hstore, text[]
- arg1 text
- arg1 integer, arg2 text, arg3 integer, arg4 integer DEFAULT NULL::integer, OUT arg5 integer, OUT arg6 integer
**Type** should be "normal" // other were among others "trigger", "agg"
**Language** should be "sql" or "plpgsql" // other were "c"
**Source code** contains the source code of the function *(could be used as comment, or not)*
**Description** could be used in the go function comment

What is interesting here is:
- the ```Argument data types``` contains the full signature
   - Incl. arg name (if provided) -> as replacement for naming with ```pggen.arg('NAME')``` - if not provided the user don't care about the name so the go function can receive nameless args no matter how much it were (arg1, arg2, arg3... or a, b, c, ...)
   - the optionality is present (DEFAULT incl. it's value)

The generated go source code, calls the postgres function, and passes optional args only if they are defined. Otherwise the arg should be omitted so that pg can use the default value (it only use it if the arg not present in the call).

---

I try to investigate more about the "record" type issue, or when this happens.
My described example however shows, that a creation of go code could be possible by directly intepreting defined functions instead of based on prepared statements.

**Comment by jschaf** [comment]
**Question 1**: For this query, what's the signature for generated Go function?

```sql
-- name: Fn1 :one
select fn1(
    pggen.arg('x')
);
```


--- 

I agree that this proposal is possible, at least for simple cases, but I have 2 concerns:

1. It's a step towards parsing the query which I've avoided so far. Postgres maintains information about the function out parameters but pggen would still have to figure out where in the query the function was called.
 
2. I think you can rewrite the function to have better type information so that pggen works out of the box. Something like below:

```sql
CREATE TYPE my_custom_type ( res_items list_item[], res_stats lists_stats );

CREATE FUNCTION fn1(
    param1 bigint,
    page int = 1,
    item_count int = 10
) RETURNS my_custom_type AS '';
```

I haven't tried, so if it's not possible, let me know.

**Comment by aight8** [comment]
My idea is to skip the whole query definition part for a defined function.
The defined function itself is the query, and a very accurate one. (regarding optional arguments, multiple out arguments)

It not solves the reflection problem. Your example 2 is exactly how I use it today.
Downside:
- I **must** use a single return type for a function.
  - Multiple ```OUT``` arguments are not supported
- I must provide a pggen query stub which calls the function
- Optional arguments are not possible

----

I try to create a full example:

**schema***
```sql
CREATE FUNCTION fn1(
    param1 bigint,
    page int = 1,
    item_count int = 10,
    OUT res_items list_items[],
    OUT res_stats lists_stats
) AS '';
```

**query**
```
// nothing
```

**generation**
```
pggen --pg-func=fn1
```

**go source**
```go
...
type Fn1OptParams struct {
   Page *int
   ItemCount *int
}

func (Querier) Fn1(param1 int, Fn1OptParams) (resItems ListItem[], resStats ListsStats, err error) {
   // ...
}
...
```
how the function parameters in return value is built up is not defined. Ideas were:
- go options design pattern
- optional arguments as separate struct with nullable fields (as above)
- 

**effectively called sql**
```sql
select fn1(param) -- when you call in go -> querier.Fn1(999)
select fn1(param, page => 1) -- when you call in go -> querier.Fn1(999, Fn1OptParams{Page: &1})
select fn1(param, page => 1, item_count => 10) -- when you call in go -> querier.Fn1(999, Fn1OptParams{Page: &1, ItemCount: &10})
select fn1(param, item_count => 10) -- when you call in go -> querier.Fn1(999, Fn1OptParams{ItemCount: &10})
```

**Comment by aight8** [comment]
```sql
select
	 l.lanname lang,
	 n.nspname "schema",
	 p.oid,
	 p.proname "name",       -- ! name // name of the function (ex: get_user_info)
	 p.prokind kind,         -- ! char // f = normal fn, p = procedure, a = aggregate fn, or w = window fn
   p.proargtypes in_arg_types,  -- ! oidvector (references pg_type.oid) // An array of the data types of the function arguments. This includes only input arguments (including INOUT and VARIADIC arguments), and thus represents the call signature of the function.
	 p.proisstrict no_null_args, -- ! bool // Function returns null if any call argument is null. In that case the function won't actually be called at all. Functions that are not “strict” must be prepared to handle null inputs.
	 p.proretset returns_many, -- ! bool // Function returns a set (i.e., multiple values of the specified data type)
   p.proargmodes arg_types,    -- ! array of: 'i' for IN, 'o' for OUT, 'b' for INOUT, 'v' for VARIADIC, 't' for TABLE -- if ALL arguments are 'i' this field will be NULL
	 p.provariadic variadic_arg_type, -- ! oid (references pg_type.oid) // Data type of the variadic array parameter's elements, or zero if the function does not have a variadic parameter
	 p.proargnames,    -- ! text[] // An array of the names of the function arguments. Arguments without a name are set to empty strings in the array. If none of the arguments have a name, this field will be null. Note that subscripts correspond to positions of proallargtypes not proargtypes.
	 p.proargdefaults  -- ! pg_node_tree // Expression trees (in nodeToString() representation) for default values. This is a list with pronargdefaults elements, corresponding to the last N input arguments (i.e., the last N proargtypes positions). If none of the arguments have defaults, this field will be null.
from pg_catalog.pg_proc p
   left join pg_catalog.pg_namespace n on n.oid = p.pronamespace
	 left join pg_catalog.pg_language l ON l.oid = p.prolang
where p.oid='get_user_info(int,int,int)'::regprocedure::oid;
```

**Comment by aight8** [comment]
I came up with another idea I want to mention (should be self-described)
The query entry have no entry.

**advantages:**
- Conflicts with polymorphic functions are more difficult because of the explicit naming like all other queries.
- Queries and function queries are all in the same place.

**disadvantages:**
- could be less flexible (by arg passing it would have been possible to define functions by wildcard, however that's implicit)

## query
```sql
-- name: WhateverFn1 :pg-func fn_name_in_pg()
-- name: WhateverFn2 :pg-func fn_name_in_pg(text)
-- name: WhateverFn2 :pg-func another_pg_fn()
```

**Comment by jschaf** [comment]
My preferred approach so far is to use a normal query file

```sql
-- name: WhateverFn
SELECT fn_name_in_pg();
```

If the function return type is a record type and the function has output parameters we can infer what the results should be. It's not clear how it should interact with other parameters:

```sql
SELECT fn_name_in_pg(), 2 as two
```

I think I'd want all the parameters at the top level instead of nesting the function output parameters.

**Comment by aight8** [comment]
I'm afrait a little when the parsing is done manually, it can end in a patchwork quilt of supported statements what pggen can intrepet correctly - and what ends in hard to understand parsing errors.
This in turn leads to great code complexity and many following issues.
The scope is unclear.

It would be hoped that the regex does not generate false positives.
In this case it would be important to define the scope - e.g. a sufficiently large list of statements that define the scope as a whole. Then possibly possible statements that just do not work, but still recognizes - the error action is already little meaningful, the parsing aggravates the situation again.

Offene Fragen:
- Ist es wirklich der Weg der gegangen werden soll?
- Wie kann der SQL geparst werden, und welche Variante würde anbetracht des definierten Scopes definitiv ausreichen? (ex: by pg itself, go pg query lib, regex)


But wouldn't the inline function alaysing build on my suggestion anyway? So this proposal could be the first step, and the inlining mechanism in a second step.

The following important advantages would nähmlich this Proposal still:
-> If I have e.g. 50 pg functions that I want to use in go, I have to create and maintain 50 pggen statments.
Additionally I cannot use optional input arguments with default value

**Comment by jschaf** [comment]
Stumbled upon a much simpler solution:

```sql
SELECT FROM fn1
```
