### ISSUE TITLE
Query Files by Glob Pattern

### ISSUE THREAD

**Issue by aight8** [jschaf/pggen#3]
```go
pggen gen go --query-file dbquery/*.sql --output-dir dbquery --postgres-connection "host=$PGHOST user=$PGUSER"
```

using go std globbing or https://github.com/bmatcuk/doublestar (just found this few days ago, and it's globbing related)

**Motivation**
I have split up all my sql files to make it managable, while development those sql files can often change or renamed.
Theoretically I could implement this globbing by a manual shell script. But because pggen support process multiple files, the globbing should be integrated.

**Comment by jschaf** [comment]
Good thought! I added support last night with doublestar in ccb44dfdd4333aac523b559ce974c3a2a690920f

```
# Notice quotes around glob to prevent shell expansion.
pggen gen go --schema-file example/erp/schema.sql  --query-glob 'example/erp/**/*.sql'
```
