### ISSUE TITLE
bug: whitespace between bracket and argument returns in error

### ISSUE THREAD

**Issue by nachtjasmin** [jschaf/pggen#34]
This query works:

```sql
-- name: FindAllArticles :many
select * from articles where name = pggen.arg('Name')
```
This one, generated by [our formatter with the default settings](https://github.com/darold/pgFormatter), does not work (notice the space between `arg` and `(`)

```sql
-- name: FindAllArticles :many
select * from articles where name = pggen.arg ('Name')
```

I think, this is related to this line, although I am not sure. https://github.com/jschaf/pggen/blob/44c162198f6e49750389d9b0befbc66d741ac6da/internal/parser/parser.go#L222

And btw, thanks for this project, I love it! 💜

**Comment by jschaf** [comment]
Thanks for reporting! I added hardcoded support for 1 space after `pggen.arg`. The correct approach is to use an expression parser, but the hardcoded matching logic is probably good enough.
