### ISSUE TITLE
Flag for package name missing

### ISSUE THREAD

**Issue by goliatone** [jschaf/pggen#48]
Is there a way to configure the package in the generated file?

Looking [here](https://github.com/jschaf/pggen/blob/main/cmd/pggen/pggen.go#L158-L167) the mapping from flags to `pggen.GenerateOptions` it seems we are missing a flag for `GoPackage`? I was expecting to be able to use a `--go-package` flag to set a custom package name.

**Comment by jschaf** [comment]
By default the package name is the same as `--output-dir`. Is the use-case to set a different package name from the output directory?

**Comment by jschaf** [comment]
Going to close. Re-open if you need something beyond what `--output-dir` does.

**Comment by bweston92** [comment]
The only issue is when using `--output-dir .` it generated `package .` which is invalid, but using `pwd` instead works.

Context

```make
all: ../../db/schema.sql
	pggen gen go --schema-glob '../../db/schema.sql' --query-glob '../../db/queries/*.sql' -output-dir "$(PWD)"

../../db/schema.sql:
	$(MAKE) -C ../../db/ schema.sql

.PHONY: clean
clean:
	rm *.sql.go
```

Would of preferred to of done

```make
all: ../../db/schema.sql
	pggen gen go --schema-glob '../../db/schema.sql' --query-glob '../../db/queries/*.sql' -output-dir . --go-package storage
```

**Comment by jschaf** [comment]
> The only issue is when using --output-dir . it generated package .

Oh, that's a silly bug worth fixing. I'll re-open with an aim of fixing that.
