### ISSUE TITLE
 cannot unmarshal number into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by bera-josh-jewell** [jschaf/pggen#54]
I am just trying to get through a basic tutorial. I installed through go install:
`go install github.com/jschaf/pggen/cmd/pggen@latest`

Then tried to run the following command against my postgres database:
`pggen gen go \
    --schema-glob author/schema.sql \
    --query-glob author/query.sql`

it creates the author schema in the database correctly, but I get the following error while trying to generate code for query.sql:
`ERROR: parse template query file "C:\\code\\api-brand-allocation\\author\\query.sql": infer typed named query FindAuthorByID: infer output types for query: infer output type nullability: explain prepared query: can't scan into dest[0]: json: cannot unmarshal number into Go value of type map[string]interface {}
`
I pulled my query.sql and schema.sql from the following location:
`https://github.com/jschaf/pggen/tree/main/example/author`

Can't figure out what I missed, hopefully something simple. Thanks!

**Comment by jschaf** [comment]
I just verified that installing via go install and running the author example works on main:

```
go install github.com/jschaf/pggen/cmd/pggen@latest
cd pggen/example
~/go/bin/pggen gen go --schema-glob author/schema.sql --query-glob author/query.sql
```

Does running the example from the repo work? My guess is that either schema file or query file has changed.  The author example doesn't use json so that's odd. Can you verify the content hasn't changed?

**Comment by bera-josh-jewell** [comment]
thanks so much for getting back to me. I just pulled the repo and then tried again. I am getting the same error. It is really odd it's complaining about json. Is that how it serializes the data?

Here is my error
![image](https://user-images.githubusercontent.com/77288157/154563759-47ec92c2-0ef7-4010-b1bb-34e590219b2d.png)

Could this have anything to do with me running on windows?

**Comment by jschaf** [comment]
I’d suspect the database setup before blaming Windows. Pggen mostly just connects to Postgres  

You’ll need Docker to run pggen without a Postgres connection. If the Docker approach works it’s probably the DB setup.

**Comment by jschaf** [comment]
Going to close as issue was resolved.
