### ISSUE TITLE
Proposal: Accessor methods for row structs

### ISSUE THREAD

**Issue by leg100** [jschaf/pggen#57]
Might it be a good idea to provide accessor methods on the row structs, specifically "getters"? Here's an example of how they help abstract across different row structs with the same fields.

```golang
type FindAuthorsRow struct {
	AuthorID  int32   `json:"author_id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Suffix    *string `json:"suffix"`
}

type FindAuthorByIDRow struct {
	AuthorID  int32   `json:"author_id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Suffix    *string `json:"suffix"`
}

type Name interface {
	GetFirstName() string
	GetLastName() string
}

func handleName(name Name) {
	first := name.GetFirstName()
	last := name.GetLastName()
	...
}

authors, _ := q.FindAuthors(context.Background(), "john")
authorByID, _ := q.FindAuthorByID(context.Background(), 123)

for _, author := range authors {
	handleName(author)
}
handleName(authorByID)

```

**Comment by leg100** [comment]
I've just seen an [identical issue for sqlc](https://github.com/kyleconroy/sqlc/pull/387), closed with a fairly reasonable objection: a generated accessor method may conflict with a field with the same name.

**Comment by jschaf** [comment]
> I've just seen an https://github.com/kyleconroy/sqlc/pull/387, closed with a fairly reasonable objection: a generated accessor method may conflict with a field with the same name.

Yea, that's a pretty good reason not to do it. I'll close this in favor of #58 which solves this issue directly.
